version: 2

jobs:
  acquire_lock:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: echo 1 - acquiring lock
      - run: sleep 30
      - run: ./.circleci/acquire_lock.sh
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: echo 2 - running tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - acquire_lock
      - test:
          requires:
            - acquire_lock

