version: 2

jobs:
  acquire_lock:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 1 - acquiring lock
      - run: sleep 3
      - run: ./acquire_lock.py
  test:
    docker:
      - image: circleci/python:2.7
    steps:
      - checkout
      - run: echo 2 - acquiring lock \w python2.7
      - run: ./acquire_lock.py

workflows:
  version: 2
  build_and_test:
    jobs:
      - acquire_lock
      - test:
          requires:
            - acquire_lock

