version: 2

jobs:
  acquire_lock:
    docker:
      - image: circleci/python:alpine
    steps:
      - checkout
      - run: echo 1 - acquiring lock
  test:
    docker:
      - image: circleci/python:alpine
    steps:
      - checkout
      - run: echo 2 - running tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - acquire_lock
      - test:
          requires:
            - acquire_lock

