version: 2

jobs:
  build:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: echo 1
  test:
    docker:
      - image: circleci/python:3.6.5
    steps:
      - checkout
      - run: echo 2

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test

