version: 2

jobs:
  acquire_lock:
    docker:
      - image: circleci/python:3.6
    environment:
      FOO: bar
      CIRCLE_TOKEN: $CIRCLE_TOKEN
    steps:
      - checkout
      - run: echo 1 - acquiring lock
      - run: sleep 3
      - run: ./acquire_lock.py
  test:
    docker:
      - image: circleci/python:3.6
    steps:
      - checkout
      - run: echo 2 - running tests

workflows:
  version: 2
  build_and_test:
    jobs:
      - acquire_lock
      - test:
          requires:
            - acquire_lock

